# Generated by Django 4.2.1 on 2023-07-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentform',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentform',
            name='sage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentform',
            name='sname',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
